name: Release Image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

env:
  IMAGE_NAME: traplace
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive version from tag
        id: ver
        run: |
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v5
        env:
          REGISTRY: ${{ secrets.REGISTRY_HOST }}
        with:
          context: .
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ secrets.REGISTRY_HOST }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.REGISTRY_HOST }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Inspect pushed manifest (sanity check)
        env:
          REGISTRY: ${{ secrets.REGISTRY_HOST }}
        run: |
          docker buildx imagetools inspect \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

