# File: .github/workflows/lint.yaml
name: CI — Lint & Conventions

on:
  pull_request:

jobs:
  python-ruff:
    name: Python (ruff)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Ruff (lint)
        run: ruff check .

      - name: Ruff (format check)
        run: ruff format --check .

  node-eslint-prettier:
    name: JS/CSS/HTML (ESLint + Prettier)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install node deps
        run: npm ci

      - name: ESLint
        run: npm run lint:js

      - name: Prettier (check)
        run: npm run format:check

  yamllint:
    name: YAML (yamllint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML
        run: yamllint .

  hadolint:
    name: Dockerfile (hadolint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          config: .hadolint.yaml
